# Generated by Django 3.1.7 on 2021-03-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
