# Generated by Django 3.1.7 on 2021-02-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210223_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created'], 'verbose_name_plural': 'replies'},
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
    ]
