# Generated by Django 3.1.7 on 2021-04-17 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210416_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
