# Generated by Django 3.1.7 on 2021-04-19 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_podcast_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='file',
        ),
        migrations.AddField(
            model_name='podcast',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
